import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-Doc Plus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          position="top-center"
          toastOptions={{
            className: "",
            style: {
              background: "var(--color-bg-secondary)",
              color: "var(--color-text-primary)",
            },
          }}
        />
        {children}</body>
    </html>
  );
}
